spring.application.name=gca

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/gca
spring.data.mongodb.database=gca

# Server
server.port=8080

# File upload configurations
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO
